[project]
name = "voice2gender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy",
    "scipy",
    "xgboost>=3.4.1",
]

[project.optional-dependencies]
dev = [
    "pandas",
    "scikit-learn",
    "ruff",
    "miniaudio>=1.71",
]
